### ISSUE TITLE
学校webvpn网址变了，登录过程也有些许变化

### ISSUE THREAD

**Issue by skyone-wzw** [onlineG2/hfut_api_service#4]
学校webvpn登录网址由`vpn.hfut.edu.cn`变成了`webvpn.hfut.edu.cn`

**Comment by skyone-wzw** [comment]
> 学校webvpn登录网址由`vpn.hfut.edu.cn`变成了`webvpn.hfut.edu.cn`

**Comment by p697** [comment]
是的，我前阵子给课本无敌版的后端更新了，忘记给这个更新了🥲
